<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <title>Verifikasi KRS</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 24px; color: #0f172a; }
        .card { max-width: 700px; margin: 0 auto; border: 1px solid #cbd5e1; border-radius: 12px; padding: 16px; }
        .ok { background: #ecfdf5; color: #166534; padding: 10px; border-radius: 8px; font-weight: 700; }
        .bad { background: #fef2f2; color: #991b1b; padding: 10px; border-radius: 8px; font-weight: 700; }
        .muted { color: #64748b; font-size: 12px; }
    </style>
</head>
<body>
<div class="card">
    <h2>Verifikasi Dokumen KRS</h2>
    @if($valid)
        <div class="ok">Dokumen valid (signature terverifikasi).</div>
    @else
        <div class="bad">Dokumen tidak valid atau tautan verifikasi kedaluwarsa.</div>
    @endif

    <p><strong>NIM:</strong> {{ $krs->mahasiswa->nim ?? '-' }}</p>
    <p><strong>Nama:</strong> {{ $krs->mahasiswa->nama ?? '-' }}</p>
    <p><strong>Tahun Akademik:</strong> {{ $krs->tahun_akademik }}</p>
    <p><strong>Semester:</strong> {{ $krs->semester_akademik }}</p>
    <p><strong>Status:</strong> {{ $krs->status }}</p>
    <p><strong>Hash Diberikan:</strong> {{ $providedHash ?? '-' }}</p>
    <p><strong>Hash Sistem:</strong> {{ $expectedHash ?? '-' }}</p>
    <p><strong>Signature:</strong> {{ !empty($validSignature) ? 'valid' : 'invalid' }} | <strong>Hash:</strong> {{ !empty($validHash) ? 'match' : 'mismatch' }}</p>
    <p class="muted">Generated by SIAKAD STAI</p>
</div>
</body>
</html>
