<?php

return [
    'menu_permissions' => [
        'menu.dashboard' => 'Dashboard',
        'menu.akademik.index' => 'Manajemen Akademik',
        'menu.akademik.tahun.index' => 'Tahun Akademik',
        'menu.akademik.jurusan.index' => 'Jurusan',
        'menu.akademik.prodi.index' => 'Prodi',
        'menu.akademik.ruangan.index' => 'Ruangan',
        'menu.akademik.kurikulum.index' => 'Kurikulum',
        'menu.akademik.matakuliah.index' => 'Mata Kuliah',
        'menu.akademik.kelas.index' => 'Kelas',
        'menu.krs.index' => 'KRS Umum',
        'menu.mahasiswa.index' => 'Data Mahasiswa',
        'menu.mahasiswa.krs' => 'KRS Mahasiswa',
        'menu.mahasiswa.khs' => 'KHS Mahasiswa',
        'menu.mahasiswa.transkrip' => 'Transkrip Mahasiswa',
        'menu.mahasiswa.tagihan' => 'Tagihan Mahasiswa',
        'menu.dosen.index' => 'Data Dosen',
        'menu.dosen.relasi.index' => 'Relasi Dosen',
        'menu.dosen.jadwal' => 'Jadwal Mengajar',
        'menu.dosen.nilai' => 'Input Nilai',
        'menu.pmb.index' => 'Form Pendaftaran PMB',
        'menu.pmb.payment' => 'Pembayaran PMB',
        'menu.pmb.verification.index' => 'Verifikasi PMB',
        'menu.landing.index' => 'Preview Website',
        'menu.settings.landing-page.index' => 'Landing Page Builder',
        'menu.keuangan.index' => 'Dashboard Keuangan',
        'menu.keuangan.tagihan' => 'Tagihan',
        'menu.keuangan.transaksi' => 'Transaksi',
        'menu.keuangan.jenis-pembayaran' => 'Jenis Pembayaran',
        'menu.keuangan.setup.index' => 'Setup Tarif',
        'menu.settings.index' => 'Pengaturan Umum',
        'menu.settings.user-access.index' => 'Manajemen User & Akses',
        'menu.settings.database.index' => 'Maintenance Database',
        'menu.settings.finance-period-locks.index' => 'Closing / Period Lock',
        'menu.settings.finance-reconciliation.index' => 'Rekonsiliasi Gateway',
        'menu.settings.payment-gateway.index' => 'Payment Gateway',
        'menu.laporan.index' => 'Laporan',
        'menu.notifications.index' => 'Notifikasi',
    ],
    'action_permissions' => [
        'action.create' => 'Akses Tambah',
        'action.update' => 'Akses Edit',
        'action.delete' => 'Akses Hapus',
    ],
];
